{
 "title": "ASP.NET Core",
 "description": "ASP.NET Core metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "prometheus",
  "aspnetcore"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(http_server_active_requests,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(http_server_active_requests{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total de solicitações",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Solicitações protegidas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (url_scheme) (\r\n    ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range]))\r\n  )",
     "legendFormat": "{{scheme}}"
    }
   ]
  },
  {
   "title": "endpoints de exceção não tratados",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", http_route!=\"\", error_type!=\"\"}[$__range])), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Conexões atuais",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kestrel_active_connections{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Total de exceções",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", error_type!=\"\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "endpoints mais solicitados",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "  topk(10,\r\n  sum by (http_route, http_request_method, method_route) (\r\n    label_join(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\", http_route!=\"\"}[$__range])), \"method_route\", \" \", \"http_request_method\", \"http_route\")\r\n  ))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Solicitação protocolo HTTP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (method_route) (\r\n    label_replace(ceil(increase(http_server_request_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__range])), \"method_route\", \"http/$1\", \"network_protocol_version\", \"(.*)\")\r\n  )",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Solicitações Atuais",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "active requests"
    }
   ]
  },
  {
   "title": "Duração das solicitações",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(\r\n  0.75,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(\r\n  0.90,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.98,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p98"
    },
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(\r\n  0.999,\r\n  sum by (le) (\r\n    rate(http_server_request_duration_seconds_bucket{job=\"api-base\"}[5m])\r\n  )\r\n)",
     "legendFormat": "p99.9"
    }
   ]
  },
  {
   "title": "Errors Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(http_server_request_duration_seconds_count{\r\n    job=\"api-base\",\r\n    http_response_status_code=~\"4..|5..\"\r\n  }[5m])\r\n)\r\n/\r\nsum(\r\n  rate(http_server_request_duration_seconds_count{\r\n    job=\"api-base\"\r\n  }[5m])\r\n)",
     "legendFormat": "All"
    },
    {
     "expr": "sum(\r\n  rate(http_server_request_duration_seconds_count{\r\n    job=~\"$job\",\r\n    instance=~\"$instance\",\r\n    http_response_status_code=~\"4..|5..\"\r\n  }[5m])\r\n)\r\n/\r\nsum(\r\n  rate(http_server_request_duration_seconds_count{\r\n    job=~\"$job\",\r\n    instance=~\"$instance\"\r\n  }[5m])\r\n)",
     "legendFormat": "4XX"
    },
    {
     "expr": "sum(\r\n  rate(http_server_request_duration_seconds_count{\r\n    job=\"api-base\",\r\n    http_response_status_code=~\"4..\"\r\n  }[5m])\r\n)\r\n/\r\nsum(\r\n  rate(http_server_request_duration_seconds_count{\r\n    job=\"api-base\"\r\n  }[5m])\r\n)",
     "legendFormat": "5XX"
    }
   ]
  },
  {
   "title": "Memória GC (.NET)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_committed_memory_size_bytes{job=\"api-base\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}